server:
  port: 3001
  host: "0.0.0.0"

ai:
  maxTokens: 8000
  temperature: 0.6
  provider: "deepseek"

game:
  personality: "疯狗玩家,见人就咬, 敢于质疑和攻击，说话直接，逻辑犀利"
  strategy: "aggressive"
  speakingStyle: "formal"

logging:
  enabled: true